version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

sphinx:
  fail_on_warning: true
  
formats:
  - pdf
  
python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
#    - requirements: requirements.txt
#    - requirements: dev-requirements.txt