language: python
python:
  - "3.8"
  - "3.9"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install .
# command to run tests
script:
  - pytest