language: python
python:
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
# command to run tests
script:
  - pytest